### ISSUE TITLE
Failing on startup

### ISSUE THREAD

**Issue by thombergs** [spring-projects-experimental/spring-cloud-sleuth-otel#93]
Hey again,

I'm currently trying to get Spring Cloud Sleuth Otel to export traces to an OpenTelemetry Collector, but I'm failing miserably :(. I finally realized I was working with an old version, but with the newest 1.0.1-M3, the Spring Boot app doesn't even start up. I guess there's an incompatibility between the Spring Cloud version I'm using and the Spring Cloud Sleuth OTel version I'm using? I couldn't find any docs on which Spring Cloud Sleuth OTel version to use with which Spring Cloud release train (I've been failing with other combinations due to different errors, but It would be great to know which ones are supposed to be compatible before continuing).

**Describe the bug**
When starting my Spring Boot app with Spring Boot `2.5.6`, Spring Cloud `2020.0.4` and Spring Cloud Sleuth `OTel 1.1.0-M3`, I get this exception on startup:

```
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.sleuth.exporter.SpanReporter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:398) ~[na:na]
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[na:na]
	... 117 common frames omitted
```

**Sample**
Here's a reproducer project with the setup that provokes the above error: https://github.com/thombergs/sleuth-otel/tree/fails-on-spanreporter (branch `fails-on-spanreporter`).

**Comment by jonatan-ivanov** [comment]
Thank you for reporting the issue, I think you are using the wrong versions, here's the compatibility matrix:

| Boot | Cloud | Sleuth-OTel|
| ---- | ----- | ---------- |
| 2.4.x, 2.5.x | 2020.0.x aka Ilford | 1.0.x | 
| 2.6.x | 2021.0.x aka Jubilee | 1.1.x | 

So you need to use the latest `1.0.x` which is `1.0.0-M12` right now.
PLease let me know if it did not work and I reopen this issue.

**Comment by jonatan-ivanov** [comment]
I added this to the readme: https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel#compatibility-matrix
